---
title: "Eleanor Jackson's CV"
author: Eleanor Jackson
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library("magrittr") # For the pipe
library("dplyr") # For mutate and filter
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1zbD2ckKDOoJX7OmeNlZuqa2tnPQmH0-7o9QqjL6n9tU/edit#gid=917338460",  
  pdf_mode = params$pdf_mode
)

# Strip descriptions from education when in CV mode
# I describe them in more detail in "research positions"
CV$entries_data <- CV$entries_data %>% 
  dplyr::mutate(description_bullets =
    ifelse(section == "education", "", description_bullets)
    )

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# if(params$pdf_mode){
#   cat("View this CV online with links at _https://github.com/ee-jackson/cv_")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/ee-jackson/cv.pdf)")
# }
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skills()
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).  -->

<!-- The source code is available [on github.com/ee-jackson/cv](https://github.com/ee-jackson/cv). -->

Last updated on `r Sys.Date()`



Main
================================================================================

Eleanor Jackson {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```



Research Experience {data-icon=flask}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('research_positions')
```



Industry Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('industry_positions')
```



Publications {data-icon=book}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('pubs_aside')
```
:::

```{r}
CV %<>% print_section('academic_articles')
```



Grants, honours & awards {data-icon=trophy}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('grants_awards')
```



Talks & posters  {data-icon=line-chart}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('talks_posters_aside')
```
:::

```{r}
CV %<>% print_section('talks_posters')
```



Teaching experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('teaching_positions')
```



Professional society affiliations {data-icon=id-card-o}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('review_aside')
```
:::

```{r}
CV %<>% print_section('societies')
```



Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('certifications')
```
