---
title: "Oli Cheal's Resume"
author: Oli Cheal
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library("magrittr") # For the pipe
library("dplyr") # For mutate and filter
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1tzSWedC-BjADADKH8Tv96YVZTIBohJ_zaRhTx2BYRTU/edit#gid=1247819769",
  pdf_mode = params$pdf_mode
)

# Now we just need to filter down the position data to include less verbose
# categories and only the entries we have designated for the resume
CV$entries_data <- CV$entries_data %>% 
  dplyr::filter(in_resume == TRUE) %>% 
  dplyr::mutate(
    # Build some custom sections by collapsing others
    section = case_when(
      section %in% c('research_positions', 'industry_positions') ~ 'positions', 
      TRUE ~ section
    )
  ) 

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# if(params$pdf_mode){
#   cat("View this CV online with links at _https://github.com/ee-jackson/cv_")
# } else {
#   cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/ee-jackson/cv.pdf)")
# }
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```

Skills {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skills()
```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- Made with the R package [**pagedown**](https://github.com/rstudio/pagedown).  -->

<!-- The source code is available [on github.com/ee-jackson/cv](https://github.com/ee-jackson/cv). -->

<!-- Last updated on `r Sys.Date()` -->



Main
================================================================================

Oli Cheal {#title}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_text_block("strapline")
```

Professional Experience {data-icon=briefcase}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('professional_experience')
```


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('education')
```


Publications {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('academic_articles')
```
